---
on:
  push:
    tags:
      - "*"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Package
        uses: crosser/ppk2tool-gtk/build-deb-action@HEAD
        id: build
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          setup-hook: ./ci-prepare.sh
          buildpackage-opts: --build=binary --no-sign
          # Output defaults to debian/artifacts directory

      - name: Upload Release
        run: >
          gh release create ${{ github.ref_name }} debian/artifacts/*
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
